apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 3
  selector:
    dc: IN
  template:
    metadata:
      name: mypod1
      labels:

        env: dev

        dc: IN

    spec:
      containers:
      - name: "mycont1"
        image: "k8s.gcr.io/echoserver:1.10"
