apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 9
  selector:
    dc: IN
  template:
    metadata:
      name: mypod1j
      labels:

        env: dev

        dc: IN

    spec:
      containers:
      - name: "mycontm"
        image: "k8s.gcr.io/echoserver:1.10"
