apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=pwd12345

resources:
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
